//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 09:14:05 pm CET 
//


package rs.ac.uns.ftn.digitalni_sertifikat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import rs.ac.uns.ftn.util.TImePrezime;
import rs.ac.uns.ftn.util.TPol;
import rs.ac.uns.ftn.util.TTest;
import rs.ac.uns.ftn.util.TVakcina;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QRCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brojSertifikata" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datumIzdavanjaSertifikata" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="imePrezime" type="{http://ftn.uns.ac.rs/util}TImePrezime"/>
 *         &lt;element name="pol" type="{http://ftn.uns.ac.rs/util}TPol"/>
 *         &lt;element name="datumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="jmbg" type="{http://ftn.uns.ac.rs/util}TJmbg"/>
 *         &lt;element name="brojPasosa" type="{http://ftn.uns.ac.rs/util}TBrojPasosa"/>
 *         &lt;element name="doza" type="{http://ftn.uns.ac.rs/util}TVakcina" maxOccurs="unbounded" minOccurs="2"/>
 *         &lt;element name="PCR" type="{http://ftn.uns.ac.rs/util}TTest"/>
 *         &lt;element name="Antigen" type="{http://ftn.uns.ac.rs/util}TTest"/>
 *         &lt;element name="Imunoloski" type="{http://ftn.uns.ac.rs/util}TTest"/>
 *         &lt;element name="datumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id_digitalni_sertifikat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qrcode",
    "brojSertifikata",
    "datumIzdavanjaSertifikata",
    "imePrezime",
    "pol",
    "datumRodjenja",
    "jmbg",
    "brojPasosa",
    "doza",
    "pcr",
    "antigen",
    "imunoloski",
    "datumIzdavanja"
})
@XmlRootElement(name = "digitalni_sertifikat")
public class DigitalniSertifikat {

    @XmlElement(name = "QRCODE", required = true)
    protected String qrcode;
    @XmlElement(required = true)
    protected String brojSertifikata;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanjaSertifikata;
    @XmlElement(required = true)
    protected TImePrezime imePrezime;
    @XmlElement(required = true)
    protected TPol pol;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumRodjenja;
    @XmlElement(required = true)
    protected String jmbg;
    @XmlElement(required = true)
    protected String brojPasosa;
    @XmlElement(required = true)
    protected List<TVakcina> doza;
    @XmlElement(name = "PCR", required = true)
    protected TTest pcr;
    @XmlElement(name = "Antigen", required = true)
    protected TTest antigen;
    @XmlElement(name = "Imunoloski", required = true)
    protected TTest imunoloski;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanja;
    @XmlAttribute(name = "id_digitalni_sertifikat")
    protected String idDigitalniSertifikat;

    /**
     * Gets the value of the qrcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQRCODE() {
        return qrcode;
    }

    /**
     * Sets the value of the qrcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQRCODE(String value) {
        this.qrcode = value;
    }

    /**
     * Gets the value of the brojSertifikata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojSertifikata() {
        return brojSertifikata;
    }

    /**
     * Sets the value of the brojSertifikata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojSertifikata(String value) {
        this.brojSertifikata = value;
    }

    /**
     * Gets the value of the datumIzdavanjaSertifikata property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanjaSertifikata() {
        return datumIzdavanjaSertifikata;
    }

    /**
     * Sets the value of the datumIzdavanjaSertifikata property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanjaSertifikata(XMLGregorianCalendar value) {
        this.datumIzdavanjaSertifikata = value;
    }

    /**
     * Gets the value of the imePrezime property.
     * 
     * @return
     *     possible object is
     *     {@link TImePrezime }
     *     
     */
    public TImePrezime getImePrezime() {
        return imePrezime;
    }

    /**
     * Sets the value of the imePrezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TImePrezime }
     *     
     */
    public void setImePrezime(TImePrezime value) {
        this.imePrezime = value;
    }

    /**
     * Gets the value of the pol property.
     * 
     * @return
     *     possible object is
     *     {@link TPol }
     *     
     */
    public TPol getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPol }
     *     
     */
    public void setPol(TPol value) {
        this.pol = value;
    }

    /**
     * Gets the value of the datumRodjenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumRodjenja() {
        return datumRodjenja;
    }

    /**
     * Sets the value of the datumRodjenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumRodjenja(XMLGregorianCalendar value) {
        this.datumRodjenja = value;
    }

    /**
     * Gets the value of the jmbg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmbg(String value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the brojPasosa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPasosa() {
        return brojPasosa;
    }

    /**
     * Sets the value of the brojPasosa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPasosa(String value) {
        this.brojPasosa = value;
    }

    /**
     * Gets the value of the doza property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the doza property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDoza().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TVakcina }
     * 
     * 
     */
    public List<TVakcina> getDoza() {
        if (doza == null) {
            doza = new ArrayList<TVakcina>();
        }
        return this.doza;
    }

    /**
     * Gets the value of the pcr property.
     * 
     * @return
     *     possible object is
     *     {@link TTest }
     *     
     */
    public TTest getPCR() {
        return pcr;
    }

    /**
     * Sets the value of the pcr property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTest }
     *     
     */
    public void setPCR(TTest value) {
        this.pcr = value;
    }

    /**
     * Gets the value of the antigen property.
     * 
     * @return
     *     possible object is
     *     {@link TTest }
     *     
     */
    public TTest getAntigen() {
        return antigen;
    }

    /**
     * Sets the value of the antigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTest }
     *     
     */
    public void setAntigen(TTest value) {
        this.antigen = value;
    }

    /**
     * Gets the value of the imunoloski property.
     * 
     * @return
     *     possible object is
     *     {@link TTest }
     *     
     */
    public TTest getImunoloski() {
        return imunoloski;
    }

    /**
     * Sets the value of the imunoloski property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTest }
     *     
     */
    public void setImunoloski(TTest value) {
        this.imunoloski = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanja(XMLGregorianCalendar value) {
        this.datumIzdavanja = value;
    }

    /**
     * Gets the value of the idDigitalniSertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdDigitalniSertifikat() {
        return idDigitalniSertifikat;
    }

    /**
     * Sets the value of the idDigitalniSertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdDigitalniSertifikat(String value) {
        this.idDigitalniSertifikat = value;
    }

}
