//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 12:02:54 PM CET 
//


package rs.ac.uns.ftn.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDrzavljanin complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDrzavljanin">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="DrzavljaninSrbije" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="StraniDrzavljaninSaPrebivalistem" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="StraniDrzavljaninBezBoravka" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDrzavljanin", propOrder = {
    "drzavljaninSrbije",
    "straniDrzavljaninSaPrebivalistem",
    "straniDrzavljaninBezBoravka"
})
public class TDrzavljanin {

    @XmlElement(name = "DrzavljaninSrbije" , required = false)
    protected Boolean drzavljaninSrbije;
    @XmlElement(name = "StraniDrzavljaninSaPrebivalistem", required = false,nillable = false)
    protected Boolean straniDrzavljaninSaPrebivalistem;
    @XmlElement(name = "StraniDrzavljaninBezBoravka", required = false)
    protected Boolean straniDrzavljaninBezBoravka;

    /**
     * Gets the value of the drzavljaninSrbije property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDrzavljaninSrbije() {
        return drzavljaninSrbije;
    }

    /**
     * Sets the value of the drzavljaninSrbije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDrzavljaninSrbije(Boolean value) {
        this.drzavljaninSrbije = value;
    }

    /**
     * Gets the value of the straniDrzavljaninSaPrebivalistem property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStraniDrzavljaninSaPrebivalistem() {
        return straniDrzavljaninSaPrebivalistem;
    }

    /**
     * Sets the value of the straniDrzavljaninSaPrebivalistem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStraniDrzavljaninSaPrebivalistem(Boolean value) {
        this.straniDrzavljaninSaPrebivalistem = value;
    }

    /**
     * Gets the value of the straniDrzavljaninBezBoravka property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStraniDrzavljaninBezBoravka() {
        return straniDrzavljaninBezBoravka;
    }

    /**
     * Sets the value of the straniDrzavljaninBezBoravka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStraniDrzavljaninBezBoravka(Boolean value) {
        this.straniDrzavljaninBezBoravka = value;
    }

}
