//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 12:02:54 PM CET 
//


package rs.ac.uns.ftn.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TStranac complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TStranac">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stranacIme" type="{http://ftn.uns.ac.rs/util}TImePrezime"/>
 *         &lt;element name="brPasos" type="{http://ftn.uns.ac.rs/util}TBrojPasosa"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStranac", propOrder = {
    "stranacIme",
    "brPasos"
})
public class TStranac {

    @XmlElement(required = true)
    protected TImePrezime stranacIme;
    @XmlElement(required = true)
    protected String brPasos;

    /**
     * Gets the value of the stranacIme property.
     * 
     * @return
     *     possible object is
     *     {@link TImePrezime }
     *     
     */
    public TImePrezime getStranacIme() {
        return stranacIme;
    }

    /**
     * Sets the value of the stranacIme property.
     * 
     * @param value
     *     allowed object is
     *     {@link TImePrezime }
     *     
     */
    public void setStranacIme(TImePrezime value) {
        this.stranacIme = value;
    }

    /**
     * Gets the value of the brPasos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrPasos() {
        return brPasos;
    }

    /**
     * Sets the value of the brPasos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrPasos(String value) {
        this.brPasos = value;
    }

}
