//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 12:02:54 PM CET 
//


package rs.ac.uns.ftn.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TTest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vrsta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="proizvodjac" type="{http://ftn.uns.ac.rs/util}TProizvodjac"/>
 *         &lt;element name="datumUzorkovanje" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="datumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="rezultat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="labaratorija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTest", propOrder = {
    "vrsta",
    "proizvodjac",
    "datumUzorkovanje",
    "datumIzdavanja",
    "rezultat",
    "labaratorija"
})
public class TTest {

    @XmlElement(required = true)
    protected String vrsta;
    @XmlElement(required = true)
    protected TProizvodjac proizvodjac;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumUzorkovanje;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanja;
    @XmlElement(required = true)
    protected String rezultat;
    @XmlElement(required = true)
    protected String labaratorija;

    /**
     * Gets the value of the vrsta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrsta() {
        return vrsta;
    }

    /**
     * Sets the value of the vrsta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrsta(String value) {
        this.vrsta = value;
    }

    /**
     * Gets the value of the proizvodjac property.
     * 
     * @return
     *     possible object is
     *     {@link TProizvodjac }
     *     
     */
    public TProizvodjac getProizvodjac() {
        return proizvodjac;
    }

    /**
     * Sets the value of the proizvodjac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProizvodjac }
     *     
     */
    public void setProizvodjac(TProizvodjac value) {
        this.proizvodjac = value;
    }

    /**
     * Gets the value of the datumUzorkovanje property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumUzorkovanje() {
        return datumUzorkovanje;
    }

    /**
     * Sets the value of the datumUzorkovanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumUzorkovanje(XMLGregorianCalendar value) {
        this.datumUzorkovanje = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanja(XMLGregorianCalendar value) {
        this.datumIzdavanja = value;
    }

    /**
     * Gets the value of the rezultat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRezultat() {
        return rezultat;
    }

    /**
     * Sets the value of the rezultat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRezultat(String value) {
        this.rezultat = value;
    }

    /**
     * Gets the value of the labaratorija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabaratorija() {
        return labaratorija;
    }

    /**
     * Sets the value of the labaratorija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabaratorija(String value) {
        this.labaratorija = value;
    }

}
