//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 12:02:54 PM CET 
//


package rs.ac.uns.ftn.obrazac;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import rs.ac.uns.ftn.util.TAdresa;
import rs.ac.uns.ftn.util.TDrzavljanstvo;
import rs.ac.uns.ftn.util.TEvidencija;
import rs.ac.uns.ftn.util.TKorisnikUstanove;
import rs.ac.uns.ftn.util.TPol;
import rs.ac.uns.ftn.util.TRadniStatus;
import rs.ac.uns.ftn.util.TSaglasan;
import rs.ac.uns.ftn.util.TTipVakcina;
import rs.ac.uns.ftn.util.TZanimanjeZaposlenog;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drzavljanstvo" type="{http://ftn.uns.ac.rs/util}TDrzavljanstvo"/>
 *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imeRoditelja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pol" type="{http://ftn.uns.ac.rs/util}TPol"/>
 *         &lt;element name="datumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="mestoRodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adresa" type="{http://ftn.uns.ac.rs/util}TAdresa"/>
 *         &lt;element name="naselje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="grad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fiksni" type="{http://ftn.uns.ac.rs/util}TFiksni"/>
 *         &lt;element name="mobilni" type="{http://ftn.uns.ac.rs/util}TMobilni"/>
 *         &lt;element name="mail" type="{http://ftn.uns.ac.rs/util}TMail"/>
 *         &lt;element name="radniStatus" type="{http://ftn.uns.ac.rs/util}TRadniStatus"/>
 *         &lt;element name="zanimanje" type="{http://ftn.uns.ac.rs/util}TZanimanjeZaposlenog"/>
 *         &lt;element name="socijalnaZastita" type="{http://ftn.uns.ac.rs/util}TKorisnikUstanove"/>
 *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opstinaSediste" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="saglasnost" type="{http://ftn.uns.ac.rs/util}TSaglasan"/>
 *         &lt;element name="vakcina" type="{http://ftn.uns.ac.rs/util}TTipVakcina"/>
 *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="evidencija" type="{http://ftn.uns.ac.rs/util}TEvidencija"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id_obrazac" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drzavljanstvo",
    "ime",
    "prezime",
    "imeRoditelja",
    "pol",
    "datumRodjenja",
    "mestoRodjenja",
    "adresa",
    "naselje",
    "opstina",
    "grad",
    "fiksni",
    "mobilni",
    "mail",
    "radniStatus",
    "zanimanje",
    "socijalnaZastita",
    "naziv",
    "opstinaSediste",
    "saglasnost",
    "vakcina",
    "potpis",
    "datum",
    "evidencija"
})
@XmlRootElement(name = "obrazac")
public class Obrazac {

    @XmlElement(required = true)
    protected TDrzavljanstvo drzavljanstvo;
    @XmlElement(required = true)
    protected String ime;
    @XmlElement(required = true)
    protected String prezime;
    @XmlElement(required = true)
    protected String imeRoditelja;
    @XmlElement(required = true)
    protected TPol pol;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected String datumRodjenja;
    @XmlElement(required = true)
    protected String mestoRodjenja;
    @XmlElement(required = true)
    protected TAdresa adresa;
    @XmlElement(required = true)
    protected String naselje;
    @XmlElement(required = true)
    protected String opstina;
    @XmlElement(required = true)
    protected String grad;
    @XmlElement(required = true)
    protected String fiksni;
    @XmlElement(required = true)
    protected String mobilni;
    @XmlElement(required = true)
    protected String mail;
    @XmlElement(required = true)
    protected TRadniStatus radniStatus;
    @XmlElement(required = true)
    protected TZanimanjeZaposlenog zanimanje;
    @XmlElement(required = true)
    protected TKorisnikUstanove socijalnaZastita;
    @XmlElement(required = true)
    protected String naziv;
    @XmlElement(required = true)
    protected String opstinaSediste;
    @XmlElement(required = true)
    protected TSaglasan saglasnost;
    @XmlElement(required = true)
    protected TTipVakcina vakcina;
    @XmlElement(required = true)
    protected String potpis;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected String datum;
    @XmlElement(required = true)
    protected TEvidencija evidencija;
    @XmlAttribute(name = "id_obrazac")
    protected String idObrazac;

    /**
     * Gets the value of the drzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link TDrzavljanstvo }
     *     
     */
    public TDrzavljanstvo getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDrzavljanstvo }
     *     
     */
    public void setDrzavljanstvo(TDrzavljanstvo value) {
        this.drzavljanstvo = value;
    }

    /**
     * Gets the value of the ime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the ime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the prezime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the prezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the imeRoditelja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeRoditelja() {
        return imeRoditelja;
    }

    /**
     * Sets the value of the imeRoditelja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeRoditelja(String value) {
        this.imeRoditelja = value;
    }

    /**
     * Gets the value of the pol property.
     * 
     * @return
     *     possible object is
     *     {@link TPol }
     *     
     */
    public TPol getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPol }
     *     
     */
    public void setPol(TPol value) {
        this.pol = value;
    }

    /**
     * Gets the value of the datumRodjenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDatumRodjenja() {
        return datumRodjenja;
    }

    /**
     * Sets the value of the datumRodjenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumRodjenja(String value) {
        this.datumRodjenja = value;
    }

    /**
     * Gets the value of the mestoRodjenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMestoRodjenja() {
        return mestoRodjenja;
    }

    /**
     * Sets the value of the mestoRodjenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMestoRodjenja(String value) {
        this.mestoRodjenja = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresa }
     *     
     */
    public TAdresa getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresa }
     *     
     */
    public void setAdresa(TAdresa value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the naselje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaselje() {
        return naselje;
    }

    /**
     * Sets the value of the naselje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaselje(String value) {
        this.naselje = value;
    }

    /**
     * Gets the value of the opstina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpstina() {
        return opstina;
    }

    /**
     * Sets the value of the opstina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpstina(String value) {
        this.opstina = value;
    }

    /**
     * Gets the value of the grad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrad() {
        return grad;
    }

    /**
     * Sets the value of the grad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrad(String value) {
        this.grad = value;
    }

    /**
     * Gets the value of the fiksni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiksni() {
        return fiksni;
    }

    /**
     * Sets the value of the fiksni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiksni(String value) {
        this.fiksni = value;
    }

    /**
     * Gets the value of the mobilni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilni() {
        return mobilni;
    }

    /**
     * Sets the value of the mobilni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilni(String value) {
        this.mobilni = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the radniStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TRadniStatus }
     *     
     */
    public TRadniStatus getRadniStatus() {
        return radniStatus;
    }

    /**
     * Sets the value of the radniStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRadniStatus }
     *     
     */
    public void setRadniStatus(TRadniStatus value) {
        this.radniStatus = value;
    }

    /**
     * Gets the value of the zanimanje property.
     * 
     * @return
     *     possible object is
     *     {@link TZanimanjeZaposlenog }
     *     
     */
    public TZanimanjeZaposlenog getZanimanje() {
        return zanimanje;
    }

    /**
     * Sets the value of the zanimanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZanimanjeZaposlenog }
     *     
     */
    public void setZanimanje(TZanimanjeZaposlenog value) {
        this.zanimanje = value;
    }

    /**
     * Gets the value of the socijalnaZastita property.
     * 
     * @return
     *     possible object is
     *     {@link TKorisnikUstanove }
     *     
     */
    public TKorisnikUstanove getSocijalnaZastita() {
        return socijalnaZastita;
    }

    /**
     * Sets the value of the socijalnaZastita property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKorisnikUstanove }
     *     
     */
    public void setSocijalnaZastita(TKorisnikUstanove value) {
        this.socijalnaZastita = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the opstinaSediste property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpstinaSediste() {
        return opstinaSediste;
    }

    /**
     * Sets the value of the opstinaSediste property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpstinaSediste(String value) {
        this.opstinaSediste = value;
    }

    /**
     * Gets the value of the saglasnost property.
     * 
     * @return
     *     possible object is
     *     {@link TSaglasan }
     *     
     */
    public TSaglasan getSaglasnost() {
        return saglasnost;
    }

    /**
     * Sets the value of the saglasnost property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSaglasan }
     *     
     */
    public void setSaglasnost(TSaglasan value) {
        this.saglasnost = value;
    }

    /**
     * Gets the value of the vakcina property.
     * 
     * @return
     *     possible object is
     *     {@link TTipVakcina }
     *     
     */
    public TTipVakcina getVakcina() {
        return vakcina;
    }

    /**
     * Sets the value of the vakcina property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTipVakcina }
     *     
     */
    public void setVakcina(TTipVakcina value) {
        this.vakcina = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpis(String value) {
        this.potpis = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the evidencija property.
     * 
     * @return
     *     possible object is
     *     {@link TEvidencija }
     *     
     */
    public TEvidencija getEvidencija() {
        return evidencija;
    }

    /**
     * Sets the value of the evidencija property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEvidencija }
     *     
     */
    public void setEvidencija(TEvidencija value) {
        this.evidencija = value;
    }

    /**
     * Gets the value of the idObrazac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdObrazac() {
        return idObrazac;
    }

    /**
     * Sets the value of the idObrazac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdObrazac(String value) {
        this.idObrazac = value;
    }

}
