//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 12:02:54 PM CET 
//


package ftn.uns.GradjaninPortalBackend.model.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTipVakcina complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTipVakcina">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Pfizer-BioNTech" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Sinopharm" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Sputnik-V" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="AstraZeneca-Oxford" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Moderna" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="BiloKoja" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * moguce vakcine:
 * "pfizerBioNTech",
    "sinopharm",
    "sputnikV",
    "astraZenecaOxford",
    "moderna",
    "biloKoja"
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTipVakcina", propOrder = {
    "tipVakcina",

})
public class TTipVakcina {

    @XmlElement(name = "tipVakcina")
    protected String tipVakcina;


    /**
     * Gets the value of the pfizerBioNTech property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public String getTipVakcina() {
        return tipVakcina;
    }

    /**
     * Sets the value of the pfizerBioNTech property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTipVakcina(String value) {
        this.tipVakcina = value;
    }

    

}
