//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 09:14:05 pm CET 
//


package rs.ac.uns.ftn.util;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.util package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.util
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TDoza }
     * 
     */
    public TDoza createTDoza() {
        return new TDoza();
    }

    /**
     * Create an instance of {@link TDrzavljanin }
     * 
     */
    public TDrzavljanin createTDrzavljanin() {
        return new TDrzavljanin();
    }

    /**
     * Create an instance of {@link TImePrezime }
     * 
     */
    public TImePrezime createTImePrezime() {
        return new TImePrezime();
    }

    /**
     * Create an instance of {@link TTest }
     * 
     */
    public TTest createTTest() {
        return new TTest();
    }

    /**
     * Create an instance of {@link TEvidencija }
     * 
     */
    public TEvidencija createTEvidencija() {
        return new TEvidencija();
    }

    /**
     * Create an instance of {@link TTipVakcina }
     * 
     */
    public TTipVakcina createTTipVakcina() {
        return new TTipVakcina();
    }

    /**
     * Create an instance of {@link TKorisnikUstanove }
     * 
     */
    public TKorisnikUstanove createTKorisnikUstanove() {
        return new TKorisnikUstanove();
    }

    /**
     * Create an instance of {@link TVakcina }
     * 
     */
    public TVakcina createTVakcina() {
        return new TVakcina();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TSrbija }
     * 
     */
    public TSrbija createTSrbija() {
        return new TSrbija();
    }

    /**
     * Create an instance of {@link TProizvodjac }
     * 
     */
    public TProizvodjac createTProizvodjac() {
        return new TProizvodjac();
    }

    /**
     * Create an instance of {@link TRadniStatus }
     * 
     */
    public TRadniStatus createTRadniStatus() {
        return new TRadniStatus();
    }

    /**
     * Create an instance of {@link TDavalacKrvi }
     * 
     */
    public TDavalacKrvi createTDavalacKrvi() {
        return new TDavalacKrvi();
    }

    /**
     * Create an instance of {@link TDrzavljanstvo }
     * 
     */
    public TDrzavljanstvo createTDrzavljanstvo() {
        return new TDrzavljanstvo();
    }

    /**
     * Create an instance of {@link TZanimanjeZaposlenog }
     * 
     */
    public TZanimanjeZaposlenog createTZanimanjeZaposlenog() {
        return new TZanimanjeZaposlenog();
    }

    /**
     * Create an instance of {@link TEkstremitet }
     * 
     */
    public TEkstremitet createTEkstremitet() {
        return new TEkstremitet();
    }

    /**
     * Create an instance of {@link TSaglasan }
     * 
     */
    public TSaglasan createTSaglasan() {
        return new TSaglasan();
    }

    /**
     * Create an instance of {@link TRednaDoza }
     * 
     */
    public TRednaDoza createTRednaDoza() {
        return new TRednaDoza();
    }

    /**
     * Create an instance of {@link TPol }
     * 
     */
    public TPol createTPol() {
        return new TPol();
    }

    /**
     * Create an instance of {@link TStranac }
     * 
     */
    public TStranac createTStranac() {
        return new TStranac();
    }

    /**
     * Create an instance of {@link TPrimljenaVakcina }
     * 
     */
    public TPrimljenaVakcina createTPrimljenaVakcina() {
        return new TPrimljenaVakcina();
    }

    /**
     * Create an instance of {@link TEvidencijaImpl }
     * 
     */
    public TEvidencijaImpl createTEvidencijaImpl() {
        return new TEvidencijaImpl();
    }

}
