//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 05:44:14 pm CET 
//


package rs.ac.uns.ftn.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDoza complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDoza">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serijaPrvaDoza" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datumDoza" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDoza", propOrder = {
    "serijaPrvaDoza",
    "datumDoza"
})
public class TDoza {

    @XmlElement(required = true)
    protected String serijaPrvaDoza;
    @XmlElement(required = true)
    protected String datumDoza;

    /**
     * Gets the value of the serijaPrvaDoza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerijaPrvaDoza() {
        return serijaPrvaDoza;
    }

    /**
     * Sets the value of the serijaPrvaDoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerijaPrvaDoza(String value) {
        this.serijaPrvaDoza = value;
    }

    /**
     * Gets the value of the datumDoza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumDoza() {
        return datumDoza;
    }

    /**
     * Sets the value of the datumDoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumDoza(String value) {
        this.datumDoza = value;
    }

}
