//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 09:14:05 pm CET 
//


package rs.ac.uns.ftn.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TEvidencija complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TEvidencija">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="evidencija" type="{http://ftn.uns.ac.rs/util}TEvidencijaImpl"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEvidencija", propOrder = {
    "evidencija"
})
public class TEvidencija {

    @XmlElement(required = true)
    protected TEvidencijaImpl evidencija;

    /**
     * Gets the value of the evidencija property.
     * 
     * @return
     *     possible object is
     *     {@link TEvidencijaImpl }
     *     
     */
    public TEvidencijaImpl getEvidencija() {
        return evidencija;
    }

    /**
     * Sets the value of the evidencija property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEvidencijaImpl }
     *     
     */
    public void setEvidencija(TEvidencijaImpl value) {
        this.evidencija = value;
    }

}
