//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 09:14:05 pm CET 
//


package rs.ac.uns.ftn.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TPrimljenaVakcina complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPrimljenaVakcina">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nazivVakcine" type="{http://ftn.uns.ac.rs/util}TTipVakcina"/>
 *         &lt;element name="datumDavanjaVakcine" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="nacinDavanjaVakcine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ekstremitet" type="{http://ftn.uns.ac.rs/util}TEkstremitet"/>
 *         &lt;element name="serijaVakcine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="proizvodjac" type="{http://ftn.uns.ac.rs/util}TProizvodjac"/>
 *         &lt;element name="nezeljenaReakcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="potpisLekara" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPrimljenaVakcina", propOrder = {
    "nazivVakcine",
    "datumDavanjaVakcine",
    "nacinDavanjaVakcine",
    "ekstremitet",
    "serijaVakcine",
    "proizvodjac",
    "nezeljenaReakcija",
    "potpisLekara"
})
public class TPrimljenaVakcina {

    @XmlElement(required = true)
    protected TTipVakcina nazivVakcine;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumDavanjaVakcine;
    @XmlElement(required = true)
    protected String nacinDavanjaVakcine;
    @XmlElement(required = true)
    protected TEkstremitet ekstremitet;
    @XmlElement(required = true)
    protected String serijaVakcine;
    @XmlElement(required = true)
    protected TProizvodjac proizvodjac;
    @XmlElement(required = true)
    protected String nezeljenaReakcija;
    @XmlElement(required = true)
    protected String potpisLekara;

    /**
     * Gets the value of the nazivVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link TTipVakcina }
     *     
     */
    public TTipVakcina getNazivVakcine() {
        return nazivVakcine;
    }

    /**
     * Sets the value of the nazivVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTipVakcina }
     *     
     */
    public void setNazivVakcine(TTipVakcina value) {
        this.nazivVakcine = value;
    }

    /**
     * Gets the value of the datumDavanjaVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDavanjaVakcine() {
        return datumDavanjaVakcine;
    }

    /**
     * Sets the value of the datumDavanjaVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDavanjaVakcine(XMLGregorianCalendar value) {
        this.datumDavanjaVakcine = value;
    }

    /**
     * Gets the value of the nacinDavanjaVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacinDavanjaVakcine() {
        return nacinDavanjaVakcine;
    }

    /**
     * Sets the value of the nacinDavanjaVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacinDavanjaVakcine(String value) {
        this.nacinDavanjaVakcine = value;
    }

    /**
     * Gets the value of the ekstremitet property.
     * 
     * @return
     *     possible object is
     *     {@link TEkstremitet }
     *     
     */
    public TEkstremitet getEkstremitet() {
        return ekstremitet;
    }

    /**
     * Sets the value of the ekstremitet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEkstremitet }
     *     
     */
    public void setEkstremitet(TEkstremitet value) {
        this.ekstremitet = value;
    }

    /**
     * Gets the value of the serijaVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerijaVakcine() {
        return serijaVakcine;
    }

    /**
     * Sets the value of the serijaVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerijaVakcine(String value) {
        this.serijaVakcine = value;
    }

    /**
     * Gets the value of the proizvodjac property.
     * 
     * @return
     *     possible object is
     *     {@link TProizvodjac }
     *     
     */
    public TProizvodjac getProizvodjac() {
        return proizvodjac;
    }

    /**
     * Sets the value of the proizvodjac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProizvodjac }
     *     
     */
    public void setProizvodjac(TProizvodjac value) {
        this.proizvodjac = value;
    }

    /**
     * Gets the value of the nezeljenaReakcija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNezeljenaReakcija() {
        return nezeljenaReakcija;
    }

    /**
     * Sets the value of the nezeljenaReakcija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNezeljenaReakcija(String value) {
        this.nezeljenaReakcija = value;
    }

    /**
     * Gets the value of the potpisLekara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpisLekara() {
        return potpisLekara;
    }

    /**
     * Sets the value of the potpisLekara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpisLekara(String value) {
        this.potpisLekara = value;
    }

}
