//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 09:14:05 pm CET 
//


package rs.ac.uns.ftn.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TSaglasan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSaglasan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="saglasanSam" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="nisamSaglasan" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSaglasan", propOrder = {
    "saglasanSam",
    "nisamSaglasan"
})
public class TSaglasan {

    protected Boolean saglasanSam;
    protected Boolean nisamSaglasan;

    /**
     * Gets the value of the saglasanSam property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSaglasanSam() {
        return saglasanSam;
    }

    /**
     * Sets the value of the saglasanSam property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSaglasanSam(Boolean value) {
        this.saglasanSam = value;
    }

    /**
     * Gets the value of the nisamSaglasan property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNisamSaglasan() {
        return nisamSaglasan;
    }

    /**
     * Sets the value of the nisamSaglasan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNisamSaglasan(Boolean value) {
        this.nisamSaglasan = value;
    }

}
