//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 09:14:05 pm CET 
//


package rs.ac.uns.ftn.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTipVakcina complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTipVakcina">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Pfizer-BioNTech" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Sinopharm" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Sputnik-V" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="AstraZeneca-Oxford" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Moderna" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="BiloKoja" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTipVakcina", propOrder = {
    "pfizerBioNTech",
    "sinopharm",
    "sputnikV",
    "astraZenecaOxford",
    "moderna",
    "biloKoja"
})
public class TTipVakcina {

    @XmlElement(name = "Pfizer-BioNTech")
    protected Boolean pfizerBioNTech;
    @XmlElement(name = "Sinopharm")
    protected Boolean sinopharm;
    @XmlElement(name = "Sputnik-V")
    protected Boolean sputnikV;
    @XmlElement(name = "AstraZeneca-Oxford")
    protected Boolean astraZenecaOxford;
    @XmlElement(name = "Moderna")
    protected Boolean moderna;
    @XmlElement(name = "BiloKoja")
    protected Boolean biloKoja;

    /**
     * Gets the value of the pfizerBioNTech property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPfizerBioNTech() {
        return pfizerBioNTech;
    }

    /**
     * Sets the value of the pfizerBioNTech property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPfizerBioNTech(Boolean value) {
        this.pfizerBioNTech = value;
    }

    /**
     * Gets the value of the sinopharm property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSinopharm() {
        return sinopharm;
    }

    /**
     * Sets the value of the sinopharm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSinopharm(Boolean value) {
        this.sinopharm = value;
    }

    /**
     * Gets the value of the sputnikV property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSputnikV() {
        return sputnikV;
    }

    /**
     * Sets the value of the sputnikV property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSputnikV(Boolean value) {
        this.sputnikV = value;
    }

    /**
     * Gets the value of the astraZenecaOxford property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAstraZenecaOxford() {
        return astraZenecaOxford;
    }

    /**
     * Sets the value of the astraZenecaOxford property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAstraZenecaOxford(Boolean value) {
        this.astraZenecaOxford = value;
    }

    /**
     * Gets the value of the moderna property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isModerna() {
        return moderna;
    }

    /**
     * Sets the value of the moderna property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setModerna(Boolean value) {
        this.moderna = value;
    }

    /**
     * Gets the value of the biloKoja property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBiloKoja() {
        return biloKoja;
    }

    /**
     * Sets the value of the biloKoja property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBiloKoja(Boolean value) {
        this.biloKoja = value;
    }

}
