//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 05:44:14 pm CET 
//


package rs.ac.uns.ftn.potvrda;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import rs.ac.uns.ftn.util.TDoza;
import rs.ac.uns.ftn.util.TImePrezime;
import rs.ac.uns.ftn.util.TPol;
import rs.ac.uns.ftn.util.TProizvodjac;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sifra" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imePrezime" type="{http://ftn.uns.ac.rs/util}TImePrezime"/>
 *         &lt;element name="datumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="pol" type="{http://ftn.uns.ac.rs/util}TPol"/>
 *         &lt;element name="jmbg" type="{http://ftn.uns.ac.rs/util}TJmbg"/>
 *         &lt;element name="brojDoze" type="{http://ftn.uns.ac.rs/util}TDoza" maxOccurs="unbounded"/>
 *         &lt;element name="zdrastvenaUstanova" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nazivVakcine" type="{http://ftn.uns.ac.rs/util}TProizvodjac"/>
 *         &lt;element name="datumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="QRCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id_potvrda" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sifra",
    "imePrezime",
    "datumRodjenja",
    "pol",
    "jmbg",
    "brojDoze",
    "zdrastvenaUstanova",
    "nazivVakcine",
    "datumIzdavanja",
    "qrcode"
})
@XmlRootElement(name = "potvrda")
public class Potvrda {

    @XmlElement(required = true)
    protected String sifra;
    @XmlElement(required = true)
    protected TImePrezime imePrezime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumRodjenja;
    @XmlElement(required = true)
    protected TPol pol;
    @XmlElement(required = true)
    protected String jmbg;
    @XmlElement(required = true)
    protected List<TDoza> brojDoze;
    @XmlElement(required = true)
    protected String zdrastvenaUstanova;
    @XmlElement(required = true)
    protected TProizvodjac nazivVakcine;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanja;
    @XmlElement(name = "QRCODE", required = true)
    protected String qrcode;
    @XmlAttribute(name = "id_potvrda")
    protected String idPotvrda;

    /**
     * Gets the value of the sifra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifra() {
        return sifra;
    }

    /**
     * Sets the value of the sifra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifra(String value) {
        this.sifra = value;
    }

    /**
     * Gets the value of the imePrezime property.
     * 
     * @return
     *     possible object is
     *     {@link TImePrezime }
     *     
     */
    public TImePrezime getImePrezime() {
        return imePrezime;
    }

    /**
     * Sets the value of the imePrezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TImePrezime }
     *     
     */
    public void setImePrezime(TImePrezime value) {
        this.imePrezime = value;
    }

    /**
     * Gets the value of the datumRodjenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumRodjenja() {
        return datumRodjenja;
    }

    /**
     * Sets the value of the datumRodjenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumRodjenja(XMLGregorianCalendar value) {
        this.datumRodjenja = value;
    }

    /**
     * Gets the value of the pol property.
     * 
     * @return
     *     possible object is
     *     {@link TPol }
     *     
     */
    public TPol getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPol }
     *     
     */
    public void setPol(TPol value) {
        this.pol = value;
    }

    /**
     * Gets the value of the jmbg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmbg(String value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the brojDoze property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the brojDoze property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrojDoze().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDoza }
     * 
     * 
     */
    public List<TDoza> getBrojDoze() {
        if (brojDoze == null) {
            brojDoze = new ArrayList<TDoza>();
        }
        return this.brojDoze;
    }

    /**
     * Gets the value of the zdrastvenaUstanova property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZdrastvenaUstanova() {
        return zdrastvenaUstanova;
    }

    /**
     * Sets the value of the zdrastvenaUstanova property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZdrastvenaUstanova(String value) {
        this.zdrastvenaUstanova = value;
    }

    /**
     * Gets the value of the nazivVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link TProizvodjac }
     *     
     */
    public TProizvodjac getNazivVakcine() {
        return nazivVakcine;
    }

    /**
     * Sets the value of the nazivVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProizvodjac }
     *     
     */
    public void setNazivVakcine(TProizvodjac value) {
        this.nazivVakcine = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanja(XMLGregorianCalendar value) {
        this.datumIzdavanja = value;
    }

    /**
     * Gets the value of the qrcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQRCODE() {
        return qrcode;
    }

    /**
     * Sets the value of the qrcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQRCODE(String value) {
        this.qrcode = value;
    }

    /**
     * Gets the value of the idPotvrda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPotvrda() {
        return idPotvrda;
    }

    /**
     * Sets the value of the idPotvrda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPotvrda(String value) {
        this.idPotvrda = value;
    }

}
