//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 09:14:05 pm CET 
//


package rs.ac.uns.ftn.izvestaj;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import rs.ac.uns.ftn.util.TRednaDoza;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datumOd" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="datumDo" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="podnetiDokumenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="primljeno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="izdato" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateVakcine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="doza" type="{http://ftn.uns.ac.rs/util}TRednaDoza" maxOccurs="unbounded"/>
 *         &lt;element name="fajzer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sputnjik" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="moderna" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sinofarm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="astraZeneca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datumIzdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id_izvestaj" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumOd",
    "datumDo",
    "podnetiDokumenti",
    "primljeno",
    "izdato",
    "dateVakcine",
    "doza",
    "fajzer",
    "sputnjik",
    "moderna",
    "sinofarm",
    "astraZeneca",
    "datumIzdavanja"
})
@XmlRootElement(name = "izvestaj")
public class Izvestaj {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumOd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumDo;
    @XmlElement(required = true)
    protected String podnetiDokumenti;
    @XmlElement(required = true)
    protected String primljeno;
    @XmlElement(required = true)
    protected String izdato;
    @XmlElement(required = true)
    protected String dateVakcine;
    @XmlElement(required = true)
    protected List<TRednaDoza> doza;
    @XmlElement(required = true)
    protected String fajzer;
    @XmlElement(required = true)
    protected String sputnjik;
    @XmlElement(required = true)
    protected String moderna;
    @XmlElement(required = true)
    protected String sinofarm;
    @XmlElement(required = true)
    protected String astraZeneca;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanja;
    @XmlAttribute(name = "id_izvestaj")
    protected String idIzvestaj;

    /**
     * Gets the value of the datumOd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumOd() {
        return datumOd;
    }

    /**
     * Sets the value of the datumOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumOd(XMLGregorianCalendar value) {
        this.datumOd = value;
    }

    /**
     * Gets the value of the datumDo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDo() {
        return datumDo;
    }

    /**
     * Sets the value of the datumDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDo(XMLGregorianCalendar value) {
        this.datumDo = value;
    }

    /**
     * Gets the value of the podnetiDokumenti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodnetiDokumenti() {
        return podnetiDokumenti;
    }

    /**
     * Sets the value of the podnetiDokumenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodnetiDokumenti(String value) {
        this.podnetiDokumenti = value;
    }

    /**
     * Gets the value of the primljeno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimljeno() {
        return primljeno;
    }

    /**
     * Sets the value of the primljeno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimljeno(String value) {
        this.primljeno = value;
    }

    /**
     * Gets the value of the izdato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIzdato() {
        return izdato;
    }

    /**
     * Sets the value of the izdato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIzdato(String value) {
        this.izdato = value;
    }

    /**
     * Gets the value of the dateVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateVakcine() {
        return dateVakcine;
    }

    /**
     * Sets the value of the dateVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateVakcine(String value) {
        this.dateVakcine = value;
    }

    /**
     * Gets the value of the doza property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the doza property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDoza().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRednaDoza }
     * 
     * 
     */
    public List<TRednaDoza> getDoza() {
        if (doza == null) {
            doza = new ArrayList<TRednaDoza>();
        }
        return this.doza;
    }

    /**
     * Gets the value of the fajzer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFajzer() {
        return fajzer;
    }

    /**
     * Sets the value of the fajzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFajzer(String value) {
        this.fajzer = value;
    }

    /**
     * Gets the value of the sputnjik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSputnjik() {
        return sputnjik;
    }

    /**
     * Sets the value of the sputnjik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSputnjik(String value) {
        this.sputnjik = value;
    }

    /**
     * Gets the value of the moderna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModerna() {
        return moderna;
    }

    /**
     * Sets the value of the moderna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModerna(String value) {
        this.moderna = value;
    }

    /**
     * Gets the value of the sinofarm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSinofarm() {
        return sinofarm;
    }

    /**
     * Sets the value of the sinofarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSinofarm(String value) {
        this.sinofarm = value;
    }

    /**
     * Gets the value of the astraZeneca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAstraZeneca() {
        return astraZeneca;
    }

    /**
     * Sets the value of the astraZeneca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAstraZeneca(String value) {
        this.astraZeneca = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanja(XMLGregorianCalendar value) {
        this.datumIzdavanja = value;
    }

    /**
     * Gets the value of the idIzvestaj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdIzvestaj() {
        return idIzvestaj;
    }

    /**
     * Sets the value of the idIzvestaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdIzvestaj(String value) {
        this.idIzvestaj = value;
    }

}
