package ftn.uns.GradjaninPortalBackend.model.interesovanje;

//

//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2022.01.09 at 12:02:54 PM CET 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import ftn.uns.GradjaninPortalBackend.model.util.TDavalacKrvi;
import ftn.uns.GradjaninPortalBackend.model.util.TDrzavljanin;
import ftn.uns.GradjaninPortalBackend.model.util.TTipVakcina;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="drzavljanin" type="{http://ftn.uns.ac.rs/util}TDrzavljanin"/>
*         &lt;element name="jmbg" type="{http://ftn.uns.ac.rs/util}TJmbg"/>
*         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="mail" type="{http://ftn.uns.ac.rs/util}TMail"/>
*         &lt;element name="mobilni" type="{http://ftn.uns.ac.rs/util}TMobilni"/>
*         &lt;element name="fiksni" type="{http://ftn.uns.ac.rs/util}TFiksni"/>
*         &lt;element name="lokacija" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="tipVakcina" type="{http://ftn.uns.ac.rs/util}TTipVakcina"/>
*         &lt;element name="davalac" type="{http://ftn.uns.ac.rs/util}TDavalacKrvi"/>
*         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/sequence>
*       &lt;attribute name="id_interesovanje" type="{http://www.w3.org/2001/XMLSchema}string" />
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "id", "drzavljanin", "jmbg", "ime", "prezime", "mail", "mobilni",
		"fiksni", "lokacija", "tipVakcina", "davalac", "datum" })
@XmlRootElement(name = "interesovanje")
public class Interesovanje {

	@XmlElement(required = true)
	protected String id;
	@XmlElement(required = true)
	protected String drzavljanin;
	@XmlElement(required = true)
	protected String jmbg;
	@XmlElement(required = true)
	protected String ime;
	@XmlElement(required = true)
	protected String prezime;
	@XmlElement(required = true)
	protected String mail;
	@XmlElement(required = true)
	protected String mobilni;
	@XmlElement(required = true)
	protected String fiksni;
	@XmlElement(required = true)
	protected String lokacija;
	@XmlElement(required = true)
	protected String tipVakcina;
	@XmlElement(required = true)
	protected Boolean davalac;
	@XmlElement(required = true)
	protected String datum;


	
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	

	/**
	 * Gets the value of the drzavljanin property.
	 * 
	 * @return possible object is {@link TDrzavljanin }
	 * 
	 */
	public String getDrzavljanin() {
		return drzavljanin;
	}

	/**
	 * Sets the value of the drzavljanin property.
	 * 
	 * @param value allowed object is {@link TDrzavljanin }
	 * 
	 */
	public void setDrzavljanin(String value) {
		this.drzavljanin = value;
	}

	/**
	 * Gets the value of the jmbg property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getJmbg() {
		return jmbg;
	}

	/**
	 * Sets the value of the jmbg property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setJmbg(String value) {
		this.jmbg = value;
	}

	/**
	 * Gets the value of the ime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIme() {
		return ime;
	}

	/**
	 * Sets the value of the ime property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setIme(String value) {
		this.ime = value;
	}

	/**
	 * Gets the value of the prezime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPrezime() {
		return prezime;
	}

	/**
	 * Sets the value of the prezime property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPrezime(String value) {
		this.prezime = value;
	}

	/**
	 * Gets the value of the mail property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * Sets the value of the mail property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMail(String value) {
		this.mail = value;
	}

	/**
	 * Gets the value of the mobilni property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMobilni() {
		return mobilni;
	}

	/**
	 * Sets the value of the mobilni property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMobilni(String value) {
		this.mobilni = value;
	}

	/**
	 * Gets the value of the fiksni property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFiksni() {
		return fiksni;
	}

	/**
	 * Sets the value of the fiksni property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setFiksni(String value) {
		this.fiksni = value;
	}

	/**
	 * Gets the value of the lokacija property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLokacija() {
		return lokacija;
	}

	/**
	 * Sets the value of the lokacija property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setLokacija(String value) {
		this.lokacija = value;
	}

	/**
	 * Gets the value of the tipVakcina property.
	 * 
	 * @return possible object is {@link TTipVakcina }
	 * 
	 */
	public String getTipVakcina() {
		return tipVakcina;
	}

	/**
	 * Sets the value of the tipVakcina property.
	 * 
	 * @param value allowed object is {@link TTipVakcina }
	 * 
	 */
	public void setTipVakcina(String value) {
		this.tipVakcina = value;
	}

	/**
	 * Gets the value of the davalac property.
	 * 
	 * @return possible object is {@link TDavalacKrvi }
	 * 
	 */
	public Boolean getDavalac() {
		return davalac;
	}

	/**
	 * Sets the value of the davalac property.
	 * 
	 * @param value allowed object is {@link TDavalacKrvi }
	 * 
	 */
	public void setDavalac(Boolean value) {
		this.davalac = value;
	}

	/**
	 * Gets the value of the datum property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDatum() {
		return datum;
	}

	/**
	 * Sets the value of the datum property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDatum(String value) {
		this.datum = value;
	}

	/**
	 * Gets the value of the idInteresovanje property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdInteresovanje() {
		return id;
	}

	/**
	 * Sets the value of the idInteresovanje property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setIdInteresovanje(String value) {
		this.id = value;
	}

}
