//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 09:14:05 pm CET 
//


package rs.ac.uns.ftn.sluzbenik.myuser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jmbg" type="{http://ftn.uns.ac.rs/util}TJmbg"/>
 *         &lt;element name="fname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mail" type="{http://ftn.uns.ac.rs/util}TMail"/>
 *         &lt;element name="mobilni" type="{http://ftn.uns.ac.rs/util}TMobilni"/>
 *         &lt;element name="fiksni" type="{http://ftn.uns.ac.rs/util}TFiksni"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brInt" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="brPot" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id_interesovanje" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jmbg",
    "ime",
    "prezime",
    "mail",
    "mobilni",
    "fiksni",
    "sifra",
    "brInt",
    "brPot"
})
@XmlRootElement(name = "MyUser")
public class MyUser {

    @XmlElement(required = true)
    protected String jmbg;
    @XmlElement(required = true)
    protected String ime;
    @XmlElement(required = true)
    protected String prezime;
    @XmlElement(required = true)
    protected String mail;
    @XmlElement(required = true)
    protected String mobilni;
    @XmlElement(required = true)
    protected String fiksni;
    @XmlElement(required = true)
    protected String sifra;
    protected int brInt;
    protected int brPot;
    @XmlAttribute(name = "id_interesovanje")
    protected String idInteresovanje;

    /**
     * Gets the value of the jmbg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmbg(String value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the fname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the fname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the lname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the lname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the mobilni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilni() {
        return mobilni;
    }

    /**
     * Sets the value of the mobilni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilni(String value) {
        this.mobilni = value;
    }

    /**
     * Gets the value of the fiksni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiksni() {
        return fiksni;
    }

    /**
     * Sets the value of the fiksni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiksni(String value) {
        this.fiksni = value;
    }


    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifra() {
        return sifra;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifra(String value) {
        this.sifra = value;
    }

    /**
     * Gets the value of the brInt property.
     * 
     */
    public int getBrInt() {
        return brInt;
    }

    /**
     * Sets the value of the brInt property.
     * 
     */
    public void setBrInt(int value) {
        this.brInt = value;
    }

    /**
     * Gets the value of the brPot property.
     * 
     */
    public int getBrPot() {
        return brPot;
    }

    /**
     * Sets the value of the brPot property.
     * 
     */
    public void setBrPot(int value) {
        this.brPot = value;
    }

    /**
     * Gets the value of the idInteresovanje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdInteresovanje() {
        return idInteresovanje;
    }

    /**
     * Sets the value of the idInteresovanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdInteresovanje(String value) {
        this.idInteresovanje = value;
    }

}
