//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 09:14:05 pm CET 
//


package rs.ac.uns.ftn.obrazac;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import rs.ac.uns.ftn.util.TAdresa;
import rs.ac.uns.ftn.util.TDrzavljanstvo;
import rs.ac.uns.ftn.util.TEvidencija;
import rs.ac.uns.ftn.util.TKorisnikUstanove;
import rs.ac.uns.ftn.util.TPol;
import rs.ac.uns.ftn.util.TRadniStatus;
import rs.ac.uns.ftn.util.TSaglasan;
import rs.ac.uns.ftn.util.TTipVakcina;
import rs.ac.uns.ftn.util.TZanimanjeZaposlenog;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drzavljanstvo" type="{http://ftn.uns.ac.rs/util}TDrzavljanstvo"/>
 *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imeRoditelja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pol" type="{http://ftn.uns.ac.rs/util}TPol"/>
 *         &lt;element name="datumRodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="mestoRodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adresa" type="{http://ftn.uns.ac.rs/util}TAdresa"/>
 *         &lt;element name="naselje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="grad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fiksni" type="{http://ftn.uns.ac.rs/util}TFiksni"/>
 *         &lt;element name="mobilni" type="{http://ftn.uns.ac.rs/util}TMobilni"/>
 *         &lt;element name="e-mail" type="{http://ftn.uns.ac.rs/util}TMail"/>
 *         &lt;element name="radniStatus" type="{http://ftn.uns.ac.rs/util}TRadniStatus"/>
 *         &lt;element name="zanimanje" type="{http://ftn.uns.ac.rs/util}TZanimanjeZaposlenog"/>
 *         &lt;element name="socijalnaZastita" type="{http://ftn.uns.ac.rs/util}TKorisnikUstanove"/>
 *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="saglasnost" type="{http://ftn.uns.ac.rs/util}TSaglasan"/>
 *         &lt;element name="vakcina" type="{http://ftn.uns.ac.rs/util}TTipVakcina"/>
 *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="evidencija" type="{http://ftn.uns.ac.rs/util}TEvidencija"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id_obrazac" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "obrazac")
public class Obrazac {

    @XmlElementRefs({
        @XmlElementRef(name = "opstina", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "prezime", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "saglasnost", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "socijalnaZastita", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "adresa", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "mobilni", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "naziv", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "naselje", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "pol", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "vakcina", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "potpis", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "e-mail", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "ime", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "drzavljanstvo", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "zanimanje", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "datumRodjenja", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "imeRoditelja", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "radniStatus", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "grad", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "datum", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "mestoRodjenja", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "fiksni", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class),
        @XmlElementRef(name = "evidencija", namespace = "http://ftn.uns.ac.rs/obrazac", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> content;
    @XmlAttribute(name = "id_obrazac")
    protected String idObrazac;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Opstina" is used by two different parts of a schema. See: 
     * line 33 of file:/D:/Projekti/XML-Vaccination/Sluzbenik%20servis/sluzbenik/src/main/resources/schemas/obrazac_o_saglasnosti.xsd
     * line 23 of file:/D:/Projekti/XML-Vaccination/Sluzbenik%20servis/sluzbenik/src/main/resources/schemas/obrazac_o_saglasnosti.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TSaglasan }{@code >}
     * {@link JAXBElement }{@code <}{@link TKorisnikUstanove }{@code >}
     * {@link JAXBElement }{@code <}{@link TAdresa }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TPol }{@code >}
     * {@link JAXBElement }{@code <}{@link TTipVakcina }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TDrzavljanstvo }{@code >}
     * {@link JAXBElement }{@code <}{@link TZanimanjeZaposlenog }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TRadniStatus }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TEvidencija }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

    /**
     * Gets the value of the idObrazac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdObrazac() {
        return idObrazac;
    }

    /**
     * Sets the value of the idObrazac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdObrazac(String value) {
        this.idObrazac = value;
    }

}
